version: '3.9'

services:
  web:
    container_name: web
    build: .
    env_file: .env
    ports:
      - 8000:8000
    volumes:
      - .:/education_app
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    environment:
      POSTGRES_DB: ${PG_DATABASE_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - 5432:5432

volumes:
  postgres_data:
