version: "3.9"

services:
  django:
    container_name: django
    build: .
    env_file: .env
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - .:/education_app
      - /static:/education_app/static
    depends_on:
      - db

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 8000:8000
    volumes:
      - ./log:/var/log/nginx
      - uwsgi_data:/tmp/uwsgi/
      - /static:/education_app/static
    depends_on:
      - django

  db:
    container_name: db
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    environment:
      POSTGRES_DB: ${PG_DATABASE_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - 5432:5432

volumes:
  uwsgi_data:
  postgres_data:
  static:
