version: '3.9'

services:
  django:
    container_name: django
    build: .
    env_file: .env
#    entrypoint: /education_app/docker-entrypoint.sh
#    ports:
#      - 8000:8000
    volumes:
      - .:/education_app
    depends_on:
      - db

  nginx:
    container_name: nginx-container
    build: ./nginx
    ports:
      - 8000:8000
    volumes:
      - ./log:/var/log/nginx
    depends_on:
      - django

  db:
    container_name: db
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    environment:
      POSTGRES_DB: ${PG_DATABASE_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - 5432:5432

volumes:
  postgres_data:
