# Generated by Django 4.1.5 on 2023-01-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'сотрудник', 'verbose_name_plural': 'сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'модуль', 'verbose_name_plural': 'модули'},
        ),
        migrations.AddField(
            model_name='employee',
            name='firstname',
            field=models.TextField(default='John'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='lastname',
            field=models.TextField(default='Smith'),
            preserve_default=False,
        ),
    ]
