# Generated by Django 4.1.5 on 2023-01-31 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_course_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
                ('completed', models.BooleanField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
            options={
                'verbose_name': 'запись о прохождении курса',
                'verbose_name_plural': 'записи о прохождении курсов',
            },
        ),
    ]
