# Generated by Django 4.1.5 on 2023-02-07 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_branch_code_alter_branch_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.AlterModelOptions(
            name='completionstatus',
            options={'verbose_name': 'запись о прохождении модуля', 'verbose_name_plural': 'записи о прохождении модулей'},
        ),
        migrations.RemoveField(
            model_name='completionstatus',
            name='course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='module',
        ),
        migrations.AddField(
            model_name='completionstatus',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.module', verbose_name='Модуль'),
        ),
        migrations.AddField(
            model_name='module',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='Курс модуля'),
        ),
        migrations.AlterField(
            model_name='completionstatus',
            name='completed',
            field=models.BooleanField(null=True, verbose_name='Модуль пройден'),
        ),
        migrations.AlterField(
            model_name='completionstatus',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Оценка за модуль'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория курса'),
        ),
    ]
